package com.ardublock.translator.block.stemdu;

import com.ardublock.translator.Translator;
import com.ardublock.translator.block.TranslatorBlock;
import com.ardublock.translator.block.exception.SocketNullException;
import com.ardublock.translator.block.exception.SubroutineNotDeclaredException;

public class I2CCompassSensorRead extends TranslatorBlock{
	public I2CCompassSensorRead(Long blockId, Translator translator) {
		super(blockId, translator);
		// TODO Auto-generated constructor stub
	}

	public I2CCompassSensorRead(Long blockId, Translator translator,
			String codePrefix, String codeSuffix) {
		super(blockId, translator, codePrefix, codeSuffix);
		// TODO Auto-generated constructor stub
	}

	public I2CCompassSensorRead(Long blockId, Translator translator,
			String codePrefix, String codeSuffix, String label) {
		super(blockId, translator, codePrefix, codeSuffix, label);
		// TODO Auto-generated constructor stub
	}

	private final static String i2ccompassFunction = "float ardublockI2CCompassSensorReadCodeAutoGeneratedReturnCM(int mode){\n  MagnetometerScaled scaled = compass.ReadScaledAxis();\n  float heading = atan2(scaled.YAxis, scaled.XAxis);\n  if(heading < 0) heading += 2*PI;\n  if(heading > 2*PI) heading -= 2*PI;\n  if(mode == 0){\n    return heading*180/M_PI;\n  }else{\n    return heading;\n  }\n}\n";
	@Override
	public String toCode() throws SocketNullException,
			SubroutineNotDeclaredException {
		// TODO Auto-generated method stub
		String outputFormat;
		TranslatorBlock translatorBlock = this.getRequiredTranslatorBlockAtSocket(0);
		outputFormat = translatorBlock.toCode();

		translator.addHeaderFile("MC5883L.h");
		translator.addHeaderFile("STEMDu.h");

		String definitionCode = "STEMDu _STEMDU_robot = STEMDu();";
		translator.addDefinitionCommand(definitionCode);
		definitionCode = "HMC5883L compass;\nint HMC5883L_error;\nfloat HMC5883L_headingOrigin;\n";
		translator.addDefinitionCommand(definitionCode);
		translator.addDefinitionCommand(i2ccompassFunction);

		translator.addSetupCommand("compass = HMC5883L();\n");
		translator.addSetupCommand("HMC5883L_error = compass.SetScale(1.3);\n");
		translator.addSetupCommand("HMC5883L_error = compass.SetMeasurementMode(Measurement_Continuous);\n");
		translator.addSetupCommand("HMC5883L_headingOrigin = ardublockI2CCompassSensorReadCodeAutoGeneratedReturnCM(" + outputFormat + ");\n");

		return codePrefix + "ardublockI2CCompassSensorReadCodeAutoGeneratedReturnCM("+outputFormat+")" + codeSuffix;
	}

}
