package com.ardublock.translator.block.stemdu;

import com.ardublock.translator.Translator;
import com.ardublock.translator.block.TranslatorBlock;
import com.ardublock.translator.block.exception.SocketNullException;
import com.ardublock.translator.block.exception.SubroutineNotDeclaredException;

public class I2CCompassSensorResetOrigin extends TranslatorBlock {
	public I2CCompassSensorResetOrigin(Long blockId, Translator translator) {
		super(blockId, translator);
		// TODO Auto-generated constructor stub
	}

	public I2CCompassSensorResetOrigin(Long blockId, Translator translator,
			String codePrefix, String codeSuffix) {
		super(blockId, translator, codePrefix, codeSuffix);
		// TODO Auto-generated constructor stub
	}

	public I2CCompassSensorResetOrigin(Long blockId, Translator translator,
			String codePrefix, String codeSuffix, String label) {
		super(blockId, translator, codePrefix, codeSuffix, label);
		// TODO Auto-generated constructor stub
	}

	private final static String i2ccompassFunction = "float ardublockI2CCompassSensorReadCodeAutoGeneratedReturnCM(int mode){\n  MagnetometerScaled scaled = compass.ReadScaledAxis();\n  float heading = atan2(scaled.YAxis, scaled.XAxis);\n  if(heading < 0) heading += 2*PI;\n  if(heading > 2*PI) heading -= 2*PI;\n  if(mode == 0){\n    return heading*180/M_PI;\n  }else{\n    return heading;\n  }\n}\n";
	@Override
	public String toCode() throws SocketNullException,
			SubroutineNotDeclaredException {
		// TODO Auto-generated method stub
		translator.addHeaderFile("MC5883L.h");
		String definitionCode = "HMC5883L compass;\nint HMC5883L_error;\nfloat HMC5883L_headingOrigin;\n";
		translator.addDefinitionCommand(definitionCode);
		translator.addDefinitionCommand(i2ccompassFunction);
		
		String ret = "HMC5883L_headingOrigin = ardublockI2CCompassSensorReadCodeAutoGeneratedReturnCM(0);\n";
		return ret;

	}
}
